---
zabbix_repo_url: "https://repo.zabbix.com/zabbix/7.4/release/debian/pool/main/z/zabbix-release/zabbix-release_7.4-1+debian12_all.deb"
zabbix_repo_env: 
  PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
conf_src: "zabbix_agent2HWSRV004.conf"
conf_dest: "/etc/zabbix/zabbix_agent2.conf"



