---
- name: Load os version on vars
  include_vars: "ubuntu{{ ansible_distribution_major_version }}.yml"

- name: Archive old zabbix_agent2.conf if it exists
  become: yes
  shell: |
    if [ -f "{{ conf_dest }}" ]; then
      cp "{{ conf_dest }}" "/etc/zabbix/zabbix_agent2.conf.backup_$(date +%Y.%m.%d)"
    fi
  args:
    executable: /bin/bash

- name: Download repo
  get_url:
      url: "{{ zabbix_repo_url }}" 
      dest: /tmp/zabbix-release.deb

- name: Install repo
  apt:
    deb: /tmp/zabbix-release.deb
  become: yes
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

- name: Update cache
  apt:
    update_cache: yes

- name: Ensure basic packages are installed
  become: yes
  apt:
    name:
      - apt-utils
      - dpkg
    state: present
    update_cache: yes

- name: Install zabbix-agent2
  apt:
    name: zabbix-agent2
    state: latest

- name: Copy zabbix_config
  copy:
    src: '{{ conf_src }}'
    dest: '{{ conf_dest }}'
    owner: root
    group: root
    mode: '0644'
  notify: restart zabbix agent

- name: Start and Run
  service:
    name: zabbix-agent2
    state: started
    enabled: yes

- name: Get zabbix-agent2 status
  shell: systemctl status zabbix-agent2
  register: agent_status
  ignore_errors: yes

- name: Status agent
  debug:
    msg: "{{ agent_status.stdout_lines }}"
